export enum ERROR_CODE_ENUM {
  // base
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // user
  ACCOUNT_ALREADY_EXISTS = 'ACCOUNT_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  USER_OR_PASSWORD_INCORRECT = 'USER_OR_PASSWORD_INCORRECT'
}
